version: '3'

services:
    redis:
        container_name: redis_container
        build:
            dockerfile: Dockerfile
            context: ./redis
        restart: always
        ports:
            - '6379:5050'
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis.conf
            - ./redis/data:/data
        image: redis-7/quark
        env_file: ./redis/.env
        